name: k8s-deploy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pillow>=10.0
  - pip
  - pip:
    - "numpy<2"
    - ultralytics>=8.1.0
    - fastapi>=0.109.0
    - "uvicorn[standard]>=0.27.0"
    - python-multipart>=0.0.6
